# note, must have space after colon before settings value
API: https://thegascloud.com/api/v1
GADGET_ID: TST_001
GASCLOUD_KEY: DEMO
UPLOAD_INTERVAL_SECS: 300
BATCH_MODE: LIVE
BATCH_TYPE: RASP
BATCH_DIR_PENDING: /home/pi/gascloud/batches2upload
BATCH_DIR_UPLOADED: /home/pi/gascloud/batchesuploaded
DELETE_BATCH_ON_UPLOAD: False
DELETE_READING_ON_ZIP: False