# Generated by Django 3.2.6 on 2021-08-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gadgetdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GadgetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('gadget_ref', models.UUIDField(db_index=True)),
                ('action_type', models.CharField(choices=[('Setup', 'Setup'), ('Updated', 'Updated'), ('Issued', 'Issued'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Location Change', 'Location Change'), ('New Batteries', 'New Batteries'), ('Battery Level', 'Battery Level'), ('Updated Calibration', 'Updated Calibration'), ('Admin info collected', 'Admin info collected'), ('Seen', 'Seen'), ('Alert', 'Alert'), ('Data Received', 'Data Received'), ('Test Data Received', 'Test Data Received'), ('Note', 'Note')], default='Updated', max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gadgets/images')),
                ('notes', models.TextField(blank=True, null=True)),
                ('when', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('where', models.CharField(blank=True, max_length=20, null=True)),
                ('who', models.CharField(blank=True, help_text='Foreign Key to user via username', max_length=36, null=True)),
                ('batchid', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gadgetdb_gadgetlog_creator', to=settings.AUTH_USER_MODEL)),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgetdb.gadget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
