# Generated by Django 3.2.6 on 2021-08-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gadgetdb', '0002_gadgetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gadget',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gadgetdb_gadget_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gadget',
            name='updated',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='gadget',
            name='updator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gadgetdb_gadget_updator', to=settings.AUTH_USER_MODEL),
        ),
    ]
