# Generated by Django 3.2.6 on 2022-06-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetdb', '0003_auto_20210813_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gadget',
            options={'ordering': ('factory_id',)},
        ),
    ]
