# Generated by Django 3.2.6 on 2021-08-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='checksum',
            new_name='rejectcountglitch',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='fan_rev_count',
            new_name='rejectcountlong',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='last_status',
            new_name='sampleflowrate',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='reject_count_glitch',
            new_name='samplingperiod',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='reject_count_longtof',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='reject_count_outofrange',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='reject_count_ratio',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='sample_flow_rate',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='sampling_period',
        ),
    ]
